---
title: "Urbanization affects web abundance and aggregation of a funnel weaver, *Agelenopsis pennsylvanica*"
author: Brandi Pessman, Madison Hays, Earl Agpawa, Eileen Hebets
date: "`r Sys.Date()`"
output: 
  bookdown::word_document2:
    reference_docx: word_styles_reference_01.docx
    fig_caption: true
    number_sections: false
bibliography: [citations.bib]
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = "/Users/bjpessman/Documents/phd_research_code/Agelenopsis_aggregation/manuscript")
require(knitr)
```

**Log line: Under increasing urbanization, generalist predators actively select web locations to effectively capitalize on more abundant prey as environmental conditions change.**

## Abstract

Animals distribute themselves within habitats based on a variety of environmental conditions, including those impacted by urbanization. In Lincoln, Nebraska, USA, funnel-weaving spiders (*Agelenopsis pennsylvanica*) are prevalent across urban habitats and actively choose web sites. We compared *A. pennsylvanica* abundance and distribution between two distinct urban habitats: an urban center and an urban forest. We searched along paths from randomly selected start sites in each habitat until we found the first occupied (focal) web. We measured web and spider abundance, distances between the focal and two nearest-neighbor webs, and web height in a ten-meter radius. We found that (i) search distances to focal webs were shorter, and both (ii) webs and (iii) spiders were more abundant in the urban center than in the urban forest, despite less diverse plants for web structures in the urban center. We also found (iv) shorter distances between webs and (v) lower web heights in the urban center. Our data suggest that *A. pennsylvanica* spatially distribute themselves differently across different urban habitats, and we discuss a variety of environmental variables that may predict this behavior. 

## Introduction

Animal abundance and distribution are influenced by combinations of environmental factors, intra- and interspecific interactions, and dispersal capacity [@svamberkova_leps_2020; @diez_pulliam_2007]. Environmental factors -- including climatic conditions, land cover, habitat heterogeneity, and access to certain resources (like water and shelter) -- are suspected to relate to physiological constraints that limit the fundamental niche [@chase_leibold_2003]. Interactions within species (between conspecific competitors and mates) and across species (with predators, prey, and heterospecific competitors) further shape animal spatial patterns [@anderson_2017; @boulangeat_2012]. While dispersal capacity can determine a species’ range, barriers can limit dispersal and prevent animals from reaching suitable habitat  [@boulangeat_2012; @amundrud_2018]. 

Aggregations can form when suitable conditions and resources are not evenly distributed, leading to higher-quality patches [@churchill_2020]. For example, gaps in the tree canopy allow more sunlight to reach the understory -- thus, increasing plant height and soil moisture and decreasing leaf litter -- causing some invertebrate families to become more abundant in these patches [@perry_2018]. Clumping can also result from incomplete dispersal that occurs when barriers, often due to habitat structure, prevent adequate dispersal [@riechert_1974b]. The relative importance of different spatial predictors can vary by the type of taxon-specific spatial information being collected -- *i.e.* presence, abundance, aggregation, or vertical position [@boulangeat_2012].

Due to intense habitat disturbance and dense human presence, urbanization has drastically modified the land [@alberti_2020]; @mcdonnell_pickett_1990; @pickett_2001) which has altered environmental conditions, community dynamics, and dispersal capability as a result [@piano_2020]. As these factors determine animal spatial patterns, it is likely that urbanized landscapes have changed how animals spatially distribute themselves, in turn. Typically, city tree cover is reduced in areas where the potential natural vegetation is forested [@nowak_1996] and greater in areas with prairie, grassland, and desert origins [@mckinney_2006]. Urban environments are additionally characterized by decreased biodiversity [@mckinney_2002] and increased impervious cover [compacted soil from buildings and pavement; @nowak_greenfield_2020] and habitat patchiness [@cadenasso_2007]. These conditions can contribute to changes in climatic conditions, such as when impervious cover traps heat and increases the average temperatures in cities compared to surrounding areas –- *i.e.*, the Urban Heat Island Effect [@morabito_2021]. 

Disturbance from human presence can also lead to air, water, and light pollution [@grimm_2008; @hopkins_2018], as well as air-borne, water-borne, and substrate-borne noise [@barber_2010; @slabbekoorn_2010; @wu_elias_2014]. There is growing evidence that urbanization changes species interactions, even reshaping whole food webs [@start_2020] and the landscape of parasite and disease transmission [@bradley_altizer_2007]. Further, habitat fragmentation and urban features often limit dispersal, which can cause higher degrees of aggregation for urban animals [@johnson_munshisouth_2017]. Urban ecosystems are extremely heterogeneous with unique and diverse habitats nested within [@rivkin_2019]. Habitats within urban ecosystems can vary considerably in feature, condition, and disturbance, resulting in variable access and distributions of resources that can differentially drive animal spatial patterns [@murray_2019; @trubl_2012]. 

Variation in the abundance and distribution of urban arthropods can have implications for ecosystem function due to the essential ecosystems services that arthropods provide, like pest control [@otoshi_2015] and pollination [@ivers_2022]. Arthropods are considered critical bioindicators of ecosystem health as their short generation time requires them to respond rapidly to human-induced change [@mcintyre_2000]. However, the impact of urbanization on arthropod ecology is still understudied [but see @kotze_2011; @fenoglio_2020], and the relationship between urban habitats and arthropod abundance and diversity remain controversial [@gippet_2017; @dale_frank_2018]. Such discrepancies are probably due to abundance and distributions being species- [@gippet_2017], habitat- [@bennett_lovell_2014], and scale-dependent [@philpott_2014]. While some animals benefit from urban conditions [@guenard_2015], many cannot survive the disturbance and change associated with cities [@wagner_2020]. Thus, it is important to determine how urban factors may be contributing to variation in arthropod abundance and spatial patterns for the conservation of arthropods and their essential services. 

Specifically, spiders play an important role in pest control and are predicted to collectively consume up to 800 million tons of arthropods each year [@nyffeler_birkhofer_2017]. Many web-building spiders are choosy in their web locations based on the distribution and abundance of other arthropod prey [@trubl_2012; @riechert_tracy_1975]. Territoriality is a form of intra-specific interactions that can also shape spatial distributions of web-builders [@riechert_1974b]. Further, previous studies have found environmental factors that vary across urban habitats may drive differences in spider spatial distribution, including noise [@bunkley_2017; @gomes_2020], pollution [@zmudzki_laskowski_2012], fragmentation [@stefani_delclaro_2015], microclimate conditions [@riechert_tracy_1975], vegetation structure [@peng_2020], and suitable web substrates [@chan_2009]. 

**This paragraph needs citations, but it will be easier after finishing the aggregation table**
The mechanisms behind solitary spider aggregations are unclear despite reports of aggregations of spiders in urban habitats, such as web-builders *Lactrodectus hesperus* and *Brigittea civica* [@johnson_et_al_2012; @mammola_et_al_2018]. This gap in knowledge is concerning as urban spider aggregations can have medical and aesthetic consequences, and implications for urban pest control services. Prey abundance seems to be an important driver because it has been shown to be directly [] and indirectly [] related to urban spider aggregations, the latter of which is shown through investigations as light sources at night as cues of prey aggregations []. Random spacing in solitary spiders is typically maintained by territoriality and aggression over resources like prey and mates [@riechert_1974b]. Occassionally, conditions arise that allow solitary spiders to become more tolerant of neighbors, and understanding these contexts can help uncover the mechanisms of aggregative behavior. Aggregations have been shown to form as a result of dispersal limitations [], predator release [], lekking reproductive strategies [], plant structure [], and environmental stressors []. The degree of aggregation in spiders can also change over time, often times more intense during juvenile stages when dispersal is limited, spreading over time as subadults and adults become more territorial [@riechert_1974b]. Studies on mechanisms of aggregations in spiders are presented and discussed in Table 1. 

Funnel weavers in the genus *Agelenopsis* actively select web locations based on experience of perceived quality of the site [@riechert_1976], and are thus likely impacted by environmental conditions resulting from urbanization. Prey abundance, available web substrates, vegetation structure, and microclimate conditions have been shown to be indicators of a quality web site in a desert habitat for *A. aperta* [@riechert_1974; @riechert_1973]. *Agelenopsis pennsylvanica* build webs that consist of a sheet that functions as a prey capture area and a retreat to escape from predators and unfavorable conditions (Fig. 1), like direct sunlight [@riechert_tracy_1975]. The horizontal sheet is not sticky, and the web is used solely for its vibratory properties to rapidly and accurately locate prey that fall upon or walk across the web [@singer_2000]. Occasionally, vertical silk strands are found that may function to capture flying prey or evade predators [@singer_2000]. The spider sits in the retreat until the prey is sensed and returns to the retreat immediately after capturing the prey. Juvenile males and females build semi-permanent webs, but males leave their web shortly after maturity in search of a receptive female [@singer_2000]. 

Understanding how urban spiders are affected by changes in environmental conditions and habitat structure brought on by processes of urbanization is vital as cities continue to densify and expand. Thus, we compared *A. pennsylvanica* spatial patterns between two urban habitats (an urban forest and an urban center) and explored what environmental factors are important determinants of web placement. In particular, we use *A. pennsylvanica* to address three questions: (*i*) How does web abundance, aggregation, and position vary between two urban habitats? (*ii*) How do environmental conditions vary between these two urban habitats? (*iii*) What environmental variables help predict spider spatial patterns in distinct urban habitats? Based on preliminary observations, we predicted that spiders would be more abundant and aggregated in the urban center than the urban forest. We further hypothesized that environmental conditions that vary between the two habitats would be correlated with the variation in the spatial patterns of *A. pennsylvanica*. 

## Material and methods

### Urban Habitats

We conducted our study in September and October of 2020 in Lincoln, Nebraska, USA. Lincoln -- with a population of about 300,000 people [@census] -- has diverse urban habitats that vary in the degree of disturbance, management, and plant cover. We compared the abundance, aggregation, and position of funnel webs (*Agelenopsis pennsylvanica*) between two urban habitats: the University of Nebraska-Lincoln (UNL) City Campus (an urban center) and Wilderness Park (an urban forest) (Fig. 2, Fig. S1). These two habitats were selected due to their distinctive characteristics (described below), preliminary observations of potential differences in funnel weaver abundance and aggregation (Fig. S2), and ease of access.

To first quantify differences in the environmental conditions between urban habitats, we gathered and analyzed Geographic Information Systems (GIS) data in QGIS (v. 3.16.3-Hannover, ESRI 102704). We obtained tree cover [@usfs_2016], impervious (building and pavement) cover [@usgs_2019_imperv], and land use class [@usgs_2019_land] from the National Land Cover Database (30-meter resolution). We used an image from path 28, row 32 of the Landsat-7 World Reference System-2 (Band 6) to collect spectral radiance -- a measure of thermal conditions on Earth's surface (30-meter resolution, taken on September 2, 2020). Finally, we assessed artificial light at night levels using the 2020 Visible Infrared Imaging Radiometer Suite (VIIRS) from https://www.lightpollutionmap.info/ (500-meter resolution). We polygonized the tiff files and calculated the average value for each factor by location: UNL City Campus, Wilderness Park, and Lincoln City Limits (see Fig. 2, Fig. S3-S6). We included measurements for Lincoln city limits to show how the two study locations compare to the city of Lincoln overall. We calculated the averages using the following equation: 

$$
average = \frac{\sum_{i = a}^{b}{i* x_i}}{100}
$$

Where *i*is the value indicated by the pixel (with range b-a) and *$x_i$* is the percent of the habitat covered by the *$i^(th)$* pixel category. These data are presented in Table 1 and summarized below.

We defined the study boundaries of UNL City Campus as Salt Creek Roadway, North Antelope Valley Parkway, North 10th Street, and Q Street (1.12 $km^2$, Fig. 2, Fig. S1). UNL City Campus is adjacent to, and just north of, downtown Lincoln (253.73 $km^2$). Impervious cover -- in the form of buildings and pavement -- dominates the land on UNL City Campus, considerably more than impervious cover across the city of Lincoln (Table 1, Fig. S3). Lawns are maintained by frequent mowing, and gardens and landscaping are regularly pruned. Tree cover on UNL City Campus and in Lincoln overall is low (< 6%, Table 1, Fig. S4). There was heavy foot traffic from UNL's 20,286 undergraduates enrolled in the 2020-2021 academic year, 37% of which lived in college-owned, -operated, or -affiliated housing [@iea_2021]. The entire area of UNL City Campus was categorized as urban with varying intensity (Table 1, Fig. 2). Over half of UNL City Campus was high intensity urban cover compared to only 13.16% for Lincoln overall. Further, UNL City Campus exhibits heighten spectral radiance (thermal conditions, Fig. S5) and artificial light at night radiance (Fig. S6), even above that of Lincoln as a whole (Table 1). Thus, we designated UNL City Campus as an *urban center* and refer to it as such hereafter.

Wilderness Park is a stretch of forested land (6.44 $km^2$, Fig. 2, Fig. S1) starting about 3.58 km southwest of UNL City Campus and downtown Lincoln, extending south and along Lincoln city limits. We found about two-fifths of Wilderness Park to be shrouded in trees (Table 1, Fig. S4), with less than 2% of its land imperviously covered (Table 1, Fig. S2). Over three quarters of Wilderness Park is categorized as forested land with only 5.44% labeled as urban (Table 1, Fig. 2). Wilderness Park has about 18 kilometers of dirt trails, dense deciduous tree growth, and variable undergrowth. The trails are open for recreational walking, running, biking, and horse riding. While we found no public records of the number of visitors to Wilderness Park, trail-goers were infrequent during data collection. Wilderness Park showed greatly reduced spectral radiance (Fig. S5) and artificial light at night radiance (Fig. S6) than the city of Lincoln (Table 1). Due to its proximity to Lincoln city limits, we designate Wilderness Park as an *urban forest* and refer to it as such hereafter.

### Study Sites and Field Measurements

Within the boundaries of the urban forest, we assigned numbers to intersections of three or more trails (Fig. S7). Similarly, we assigned numbers to each intersection of roads and sidewalks that meet from the four cardinal directions in the urban center (Fig. S7).  We used a random number generator to randomly select 10 intersections in the urban forest and 12 intersections in the urban center as start sites (Table S1). We marked the GPS coordinates of these locations using a GPS receiver (Magellan SporTrak Map, Model 980616-01, Parsippany, New Jersey, USA).

From each start site, we began walking along a path in a randomly selected direction (North, East, South, or West using a random number generator). We thoroughly searched the edges of the path for funnel webs as the GPS receiver tracked our movement (Fig. S8). We walked along pre-existing sidewalks, roads, and trails because paths were a common feature of both habitats along which we had previously found funnel weavers. We often find *A. pennsylvanica* in edge habitats in the study region, and this tendency to build webs at a habitat's edge is shared by other spider species [@cobbold_supp_2012]. Additionally, the thick undergrowth of the urban forest often restricted searches off the trails. To ensure equivalent search efforts, we took more time searching the edge of dense undergrowth in the urban forest.

When we reached a funnel web, we checked to see if the web was occupied by a spider by resting a toothpick secured to the bristled end of a vibrating toothbrush on the sheet of the web to simulate prey in the web. If a spider emerged, we noted this web as the *focal web*. If no spider emerged after 30 seconds, we continued searching until we found an occupied funnel web. We used the GPS receiver to mark the coordinates of the focal web. Although it is possible that other species of *Agelenopsis* are present in Lincoln, we have only found *A. pennsylvanica* during surveys in the area.

Search distance can often be used to estimate abundance [@buckland_2005], as spiders are likely less abundant in an area where we need to search further from the start site to the focal web. Thus, we use search distance as evidence for variation in abundance. To quantitatively determine the abundance of webs and spiders near each focal web, we measured a ten-meter radius around the focal web and counted the number of occupied and unoccupied webs determined in the same manner as the focal web. We also assessed nearest neighbor distances as a measure of aggregation behavior. Starting at the focal web and working outwards, we marked the locations of the two webs (including occupied and unoccupied) nearest to the focal web within ten meters. We limited our measurements to the nearest two webs because we often found no more than three webs (including the focal web) per site in the urban forest. We measured the shortest distance from the retreat of the focal web to the retreat of the two nearest neighbor webs. To explore differences in web placement, we measured the web height from the ground to the web retreat for every web with the ten-meter radius. Differences in web height have been shown to vary by environmental factors associated with urbanization [@dahirel_2017]. To get an idea of plant species richness at each site, we recorded each unique plant species found in a ten-meter radius of the focal web (Fig. S8). 

We collected data from September 23 to October 14, 2020. During these dates, all *A. pennsylvanica* have reached maturity [@guarisco_2014; personal observation]. Of the 64 occupied webs, 61 were occupied by females indicating that males had likely abandoned their webs in search of females. The 67 unoccupied webs could be those once owned by males or those abandoned by females. While webs were found on many of the same plant types between sites in the urban forest and urban center in varying proportions, 15% of webs in urban center sites were built on non-plant substrates (Fig. S9).

### Environmental Predictors

To assess potential mechanisms behind variation in abundance, aggregation, and position, we looked for correlations between spider spatial patterns and environmental conditions -- collected in the field (plant species richness) or using GIS for each site. In QGIS, we created 100 meter buffers around each focal web location and processed the GIS variables mentioned above (tree cover, impervious cover, spectral radiance, and artificial light at night radiance) in the same manner as before. To these we added patch area, potential disturbance from nearby roads and highways, and road length in the 100 meter buffer. We used a 100 meter buffer to accommodate the resolution of the GIS data. We refrained from including a larger buffer region as the dispersal range of this system is unknown and may be dependent on barriers present in the habitat.

We measured patch area using satellite imagery to define the area of continuous vegetation around the focal web. Roads, sidewalks, and trails were defined as fragment boundaries. To determine the potential disturbance from road and highway traffic, we first measured the shortest distance from each focal web to the nearest road [GIS vector from: @centerlines] and highway [GIS vector from: @highways] using the NNJoin Plugin [@nnjoin] for QGIS. We used the 2021 Average Daily Traffic Volume report [@adtv_2021] to identify the average daily number of vehicles to travel on each nearest road and highway. We divided the average daily traffic by the shortest distance from the focal web to the nearest road and highway [as in @dooley_2020] for metrics of road disturbance and highway disturbance, respectively. Lastly, we measured the total length of road [@centerlines] within a 100 meter buffer of the focal web.  

### Statistical Analysis

#### Web abundance, aggregation, and position between habitats

For the first set of models, we focused on whether web abundance, aggregation, and position differ between the two habitats (the urban center and urban forest). We used Poisson generalized linear models [*stats* package in R, @stats] for the response variables: search distance, number of webs, and number of spiders. We used Poisson generalized linear mixed effect models [*lme4* package in R, @lme4] with site as a random effect for the response variables: nearest neighbor distance and web height. For the model with nearest neighbor distance, we also included neighbor number (nearest and second nearest web) and its interaction with habitat We used Poisson distributions because the response variables were not normally distributed according to Shapiro-Wilk Normality Tests, and all data were strictly positive with no upper limit. 

#### Environmental variables between habitats

Since we found significant variation in distribution measures between habitats, we wanted to explore potential environmental mechanisms of such variation within the test habitats. We first tested whether the nine environmental predictors varied by habitat (Table 2). Each predictor was tested by habitat using Poisson generalized linear models as the predictors were positive and not normally distributed. Each environmental predictor significantly varied by habitat (Table 2), so we subset the data by habitat. Among the environmental predictors, we removed variables that were highly correlated (cutoff of 0.6) using the *caret* package in R [@caret]. Artificial light at night radiance was dropped from all analyses for being highly correlated. Only plant species richness, road disturbance, and highway disturbance remained for models using all data. We kept tree cover, plant species richness, patch area, and road and highway disturbance for the urban forest subset. The urban center subset includes plant species richness, patch area, spectral radiance, road and highway disturbance, and road length. 

#### Model selection for environmental predictors of spatial patterns

We used the habitat subsets and the selected environmental predictor variables to assess correlations between predictor variables and spatial pattern measures. In the global models, we included the predictors that remained after removal for collinearity (no interactions) with the response variables: web and spider abundance, nearest neighbor distance, and web height for the complete data and habitat subsets. We assessed nearest neighbor distance and excluded second nearest neighbor distance because both were significantly different between habitats. We excluded search distance as a response variable because the predictors were collected from the site of the focal web and may vary along the search path. Several predictors (plant species richness, patch area, and road and highway disturbance) were highly right-skewed, so we used a natural log-transformation prior to model selection. We used Poisson generalized linear models for number of webs and spiders and nearest neighbor distance and Poisson generalized linear mixed-effect models for web height with site as a random effect. From these global models, we performed Akaike Information Criterion (AIC) model selection with the *MuMIn* package in R [@MuMIn], which ranks models produced from every combination of the predictors in the global model. We report here the results of each top model, as well as a model average of models within 2 delta AICc points of the top model. We reported the estimates and standard error from the models without back-transformations for the log-transformed variables. We checked that the Variance of Inflation (VIF) stayed at or below a score of two for predictors in each top model using the *car* package in R [@car]. 

We also explore how land use may affect web abundance, aggregation, and position using the National Land Cover Database and QGIS to record the category of the land use type for the pixel that each site was located. We tested Poisson generalized linear models for each response variable with land cover as the only predictor. We used the *Anova()* function in the *car* package [@car] to get the Likelihood Ratio Chi-Squared values, then used the *glht()* funtion in the *multcomp* package [@multcomp] to perform pairwise comparisons among categories. We include these results in supplemental material (Fig. S12, Table S3) as the sample sizes were small (deciduous forest = 7, woody wetlands = 3, urban high intensity = 4, urban medium intensity = 6, urban low intensity = 2).

We completed statistics and visualization using R 4.0.0 [@r] and RStudio 2022.07.2 [@rstudio]. All graphs show raw data and (top) model estimates (*broom* package [@broom]; *emmeans* package [@emmeans]). We used the *tidyverse* [@tidyverse], *ggpubr* [@ggpubr], and *broom.mixed* [@broommixed] packages in R to produce and customize the graphs. The *flextable* package [@flextable] was used to produce the tables. For Poisson generalized linear mixed effect models, we determined the 95% confidence intervals of the model estimates by completing 1000 bootstrap iterations using the function *bootMer()* in R package *lme4* [@lme4]. All R code and data are available in a GitHub repository at: https://github.com/brandipessman/Agelenopsis_aggregation.

## Results

### Web abundance, aggregation, and position between habitats

All abundance, aggregation, and position metrics -- search distance, the number of webs and spiders within 10 meters of the focal web, the distance from the focal web to the two nearest neighbor webs, and web height -- varied by habitat (Fig. 3). 

We searched significantly less distance from the start site to the focal web in the urban center than the urban forest ($z_20$ = -10.10, *P* < 0.001, Fig. 3a, Fig. S8). Within a 10-meter radius of the focal web, we counted significantly more webs ($z_20$ = 8.56, *P* < 0.001, Fig. 3b) and spiders ($z_20$ = 4.86, *P* < 0.001, Fig. 3c) in the urban center than the urban forest. We also found that the distances between the focal web and the two nearest neighbors were significantly shorter in the urban center than the urban forest ($z_34$ = -5.60, *P* < 0.001, Fig. 3d). By definition, the second nearest web is further from the focal web than the nearest neighbor ($z_34$ = 14.65, *P* < 0.001). There was a significant interaction between neighbor number and habitat -- the second nearest neighbor was significantly further from the focal web than the first nearest neighbor in the urban center, but not the urban forest ($z_34$ = 9.86, *P* < 0.001, Fig. 3d). Lastly, webs were built lower in the urban center than the urban forest ($z_128$ = -2.38, *P* = 0.017, Fig. 3e). This difference was not due to differences in substrate height because we found no difference in substrate height between habitats ($z_128$ = -1.10, *P* = 0.273). 

### Environmental differences between habitats

All environmental predictors assessed within a 100-meter radius of the focal web varied by habitat (Table 2). Site tree cover was lower in the urban center than the urban forest with five urban center sites with zero tree cover ($z_21$ = -14.50, *P* < 0.001). The urban center sites had higher impervious cover while all but four sites were zero in the urban forest ($z_21$ = 14.51, *P* < 0.001). The urban center sites also had higher spectral radiance ($z_21$ = 3.08, *P* = 0.002) and artificial light at night radiance ($z_21$ = 22.46, *P* < 0.001). Overall plant species richness was lower in the urban center than the urban forest ($z_21$ = -7.67, *P* < 0.001). Similarly, spiders used a lower diversity of plants as substrates in the urban center (mean ± se = 1.42 ± 0.15 species) than the urban forest (mean ± se = 2.7 ± 0.26 species, $z_21$ = -2.08, *P* = 0.037). Site patch area was smaller in the urban center ($z_21$ = -374.2, *P* < 0.001). Road disturbance ($z_21$ = 39.19, *P* < 0.001), highway disturbance ($z_21$ = 9.39, *P* < 0.001), and road density ($z_21$ = -374.2, *P* < 0.001) were higher for urban center sites than sites in the urban forest. The urban forest sites had an average total trail length of 113 ± 11.3 meters within 100 meters of the focal web.

### Environmental predictors of abundance, aggregation, and position

To explore potential mechanisms of variation in spatial patterns, we looked for correlations between response variables (number of webs, number of spiders, nearest neighbor distance, and web height) and environmental predictors overall and within each habitat (Table 3, Table S2, Fig. 4-5).

The top models for the number of webs and the number of spiders yielded similar results (Table 3, Fig. 4). For both measures of abundance, the urban forest subset retained no predictors (Table 3) while the urban center showed a decrease in abundance with increasing plant species richness, patch area, highway disturbance, and road length (Table 3, Fig. 4). The model average for the number of webs subset by urban center suggested similar results (Table S2). Plant species richness and highway disturbance both had a negative relationship with abundance measures for the overall data set (Table 3, Fig. S11). Interestingly, the top model of web abundance retained road disturbance and suggested a positive relationship overall (Table 3, Fig. S11). 

Overall, spiders are closer together when plant species richness is low and when road disturbance is high (Table 3, Fig. S11). On the other hand, less tree cover, lower road and highway disturbance, and greater plant species richness are associated with nearness in the urban forest (Table 3, Fig. 5), however, this model was a poor fit ($R^2$ = 0.037). Urban center spiders are more aggregated where plant species richness, spectral radiance, and road length are high (Table 3, Fig. 5). The model average for the nearest neighbor distance in the urban center corroborates these findings and adds that webs are clumped when patch area is larger (Table S2). 

Further, webs are built higher overall when the number of plant species is higher (Table 3, Fig. S11). A trend also suggests that lower webs are associated with higher road disturbance, although this result is not significant (Table 3, Fig. S11). In the urban forest, web height is positively related to tree cover (Table 3). While plant species richness was included in the top model, it did not vary by web height in the urban center (Table 3). We see similar results from the model averages for web height (Table S2). Despite the addition of predictors under the model averages, none of the added predictors varied by web height in their respective data sets (Table S2). 

For statistical analysis and figures of response variables by land cover class, see supplemental material (Table S3, Fig. S12). Following Likelihood Ratio tests, we find that all response variables significantly vary by land cover class (Table S3). There was no difference in search distance between deciduous forest, urban medium intensity and urban low intensity. However, we searched significantly further in woody wetlands and significantly shorter in urban high intensity (Fig. S12a). The number of webs and spiders only varied by habitat - urban low, medium, and high intensity had more webs and spiders than deciduous forest or woody wetlands (Fig. S12a-b). Nearest neighbor distance was shorter for woody wetlands than deciduous forest (Fig. S12d). For the urban intensities, web distance was shortest at low intensities and furthest at medium intensities with high urban intensity suggest web height between low and medium intensities (Fig. S12d). Lastly, web height showed no difference between land cover class with pairwise comparisons (Fig. S12e).

## Discussion

### Spiders are more abundant in the urban center

Both webs and spiders of *A. pennsylvanica* were more abundant in the urban center than the urban forest. Shorter search distances to the focal web corroborates this finding, as previous studies have used search distance as an estimate of abundance [@buckland_2005, @kral_2018]. Tolerance of urban ecosystems is dependent on the ecology and behavior of the organism, such as being a generalist consumer [@sol_2013; @bang_2011], and the scale of the measurements being collected [@lowe_2018; @philpott_2014], resulting in conflicting findings in the literature. While arthropods are generally found to decline [@wagner_2020; @piano_2020], generalists and thermally flexible species are more likely to be urban exploiters than specialists or thermally inflexible species [@callaghan_2021]. For example, *Nephila plumipes*, a generalist predator, was found to abundantly occupy urban habitats where prey abundance supported greater numbers of spiders [@lowe_2016]. Prey abundance has been repeatedly found to be a strong predictor of spider abundance [@trubl_2012, @parkinson_2020, @harwood_2001]. While we did not measure intra- and interspecific interactions between the two urban habitats studied here -- although future research on this system should test these biotic factors -- , we did find several environmental factors that may predict spider abundance directly or indirectly through environmental effects on prey, predator, or competitor abundance or dispersal limitations.

**need to talk more about predator and competitor abundance? - I think not, mention in next paragraph.**

The environmental conditions assessed here only correlated with web and spider abundance in the urban center, with no strong environmental effects on abundance in the urban forest. Variation in abundance per urban forest site was low, only ranging from two to four webs and one to three spiders. On the other hand, abundance for webs ranged from one to 73 webs and one to 22 spiders per urban center site. Additionally, urban forest abundance may be better predicted by factors not assessed here, such as prey and predator abundance or dispersal limitation [@harwood_2001; @bonte_et_al_2003]. In the urban center, web and spider abundance was higher when plant species richness, patch area, highway disturbance, and road length were lower. *Agelenopsis pennsylvanica* rely heavily on vibrations to capture prey [@riechert_maupin_1998], court potential mates [@singer_2000], and potentially evade predators [@riechert_hedrick_1990]. Thus, we suspect that vibratory noise may play a key role in web site selection, choosing sites that mitigate these effects. We show that webs and spiders are more abundant in urban center sites that had lower highway disturbance and total length of road in a 100-meter radius. Although research on the effects of noise on arthropod behavior has focused on acoustic rather than vibratory noise [@roberts_howard_2022], studies have found strong negative effects of acoustic and vibratory noise on arthropod behavior [@carosi_et_al_2019; @bunkley_et_al_2017]. A recent study shows that the orb-weaving spider, *Larinioides sclopetarius* is able to detect airborne sound that induces vibrations in the web [@zhou_et_al_2022]. 

Since different plants transmit vibrations differently [CITE], selective spiders in urban habitats may choose plants web substrates that reduce vibratory noise. Our results show that spiders are more abundant when plant species richness is lower. The urban center sites were covered in grass lawns and managed landscaping that usually had few plant species present. Sites with lower plant diversity may have few plant species that are highly preferred, leading to higher spider abundance. Greater plant diversity has been found to have both positive and negative affects on spider abundance, and some suggest that plant community composition tends to play a vital role [CITE]. To better understand the role that plant species play in abundance would require comparing plant communities between patches used by spiders versus those devoid of spiders. Additionally, smaller patches were associated with higher spider abundance. While arthropods overall tend to decrease in abundance as smaller patch sizes, habitat generalists and edge specialists can be found at greater abundance in smaller patches [CITE].

### Spiders are more aggregated in the urban center

Both the first and second nearest neighbor webs to the focal web were closer in the urban center than the urban forest. Multiple reports have found spider aggregations in urban habitats [], especially when related to the abundance of prey. Territoriality over mates and prey resources often drives random spacing of solitary species [], but aggregations can form when abundant resources allow for increased tolerance of neighbors []. Light at night in cities attracts insects creating pockets of increased prey abundance for spiders. As such, spiders have been found to aggregate under light sources. Although we did not measure microhabitat levels of light at night or prey abundance, *A. pennsylvanica* were more aggregated in the urban center where light at night radiance was higher than the urban forest. Future research should address both direct and indirect indicators of prey abundance in aggregations of spiders in urban habitats. 

To determine whether nearness of neighbors in the urban center was the result of aggregation or just increased density from higher abundance, we completed calculations described by Clark and Evans [@clark_evans_1954]. This calculation compares the measured nearest neighbor distance to the expected distance if animals were evenly spaced within an area. A ratio value significantly below 1 suggests clumping, while values that do not significantly differ from 1 indicate random spacing. For each site, we estimated the total search area by adding the length of path searched multipled by four meters (for searching two meters on either side of the central path line) and the area of the 10 meter radius circular site. We subtracted the overlap in the search path and site by subtracting four * 10 meters. We find that webs are clumped in the urban center (R = 0.47, P < 0.01) and uniform in the urban forest (R = 1.24, P > 0.05). We conclude that aggregations formed for reasons other than increased spider density. 

We found significant relationships between environmental predictors and nearest neighbor distance in both urban habitats. Urban center and forest spiders responded differently in aggregative behavior in response to vibratory noise measures -- urban forest spiders aggregated at lower road and highway disturbance and urban center spiders aggregated more there was more road within 100 meters of the focal web, but did not vary by road or highway disturbance. As a result, noise might affect urban forest spiders more than spiders reared in or that are decendents from the urban center where noise is greater. Spiders in the urban forest may exhibit increased nearest to neighbors if higher quality web locations are those that are further from road disturbance. Many spiders are thought to be plastic in the structure and tuning of their webs, and urban exploiters are often fast to adjust to changing conditions, so spiders in the urban center might be able to better tune their webs to decrease vibrations, although this hypothesis requires further testing. It will also be important to differentiate whether these differences in behavior between environments is based on developmental exposure, behavioral plasticity, or genetic differentiation. 

Higher plant species richness led to greater aggregation for spiders in both the urban center and the urban forest. We speculate that greater aggregation on more diverse plant communities may suggest that *A. pennsylvanica* prefers a certain plant or type of plant, especially in urban centers where similar plants are often clumped in space for landscaping. In the urban forest, we also found nearer neighbors under less tree cover. A study that measured invertebrate abundance after manipulating tree cover found that newly formed tree gaps have greater vegetation height and coverage and increased soil moisture and temperature, all of which led to an overall increase in invertebrate abundance -- a result that had been corroborated by other studies. Since spider aggregations tend to occur where prey abundance is higher, we might predict that lower tree cover might indirectly increase spider aggregation through an increase in prey abundance. Lastly, spiders in the urban center were more aggregated at sites with higher spectral radiance (a measure of surface temperature). Urban centers tend to be warmer on average compared to surrounding areas due to heat trapping via pavement in a phenomenon called the Urban Heat Island Effect. Aggregation formation in warmer sites could be the result of limited shelter from excessive heat or from a preference for warmer areas.

### Web heights were lower in the urban center

We found that the height of the webs built by spiders in the urban center were built lower than webs in the urban forest, and this result was independent of the height of the substrate. Webs may vary in height based on the type of prey being ensnared. *Agelenopsis* spiders capture both flying and crawling insects []. Arthropod community structure is highly variable between urban habitats, and urban centers and urban forests may support different types of prey items for *A. pennsylvanica*. Lower webs in the urban center may be ideal for more crawling prey while higher webs in the urban forest may better trap flying insects. Alternatively, webs in different habitats may experience different levels of disturbance. In the urban center where lawns are mown frequently and ornamental plants are regularly pruned, spiders could maintain lower webs to conserve energy from constantly climbing up a substrate. Urban forests likely have abundant ground dwelling vertebrates whose movement along the forest floor could frequently damage lower webs. Greater tree coverage in the urban forest predict higher webs may further suggest that small mammal movement could destroy low wbes as areas with greater tree cover have been shown to have higher abundance of small mammals []. Future research should assess prey type available and small animal abundance and movement between these two habitats. We speculate that vibratory noise may promote lower web heights based on a trend that showed lower web heights overall at sites with higher road disturbance. Plant vibrations tend to be dampened nearer to the ground [] which could encourage spiders to build lower where noise is reduced. 

## Conclusions

Our study shows that a solitary, generalist predator is more abundant and aggregated with lower web height in an urban center compared to an urban forest -- habitats that vary signficantly in environmental condition. While we did not measure community-level interactions among organisms, correlations between spatial pattern and environmental condition indirectly indicate that inter- and intraspecific interactions, especially prey abundance, are essential for predicting and monitoring spider aggregative behavior. Spider aggregations in urban centers can have medical consequences, such as dense *Lactrodectus hesperus* aggregations [], and aesthetic conerns, as is the case with aggregations of ** under archways of historic buildings []. On the other hand, spider aggregations could control pest outbreaks that threaten human health and food supply. We emphasize that elucidating the complex relationship between the arthropod abundance and the impacts of urbanization is essential for our understanding of how urbanization affects ecosystem services and food web interactions. Our variables that estimate the potential for vibratory noise negatively affected spider abundance while promoting lower web heights, potentially to reduce interference from vibratory noise. Noise variables had opposite affects on aggregative behavior of spiders in the different habitats that may indicate differences in tolerance to noise, but more research is necessary to test this hypothesis. Thus, urban habitats can vary in environmental conditions which can determine how animals distribute themselves in space and affect predator-prey interactions. 

\newpage
## References {-}
<div id="refs"></div>
\newpage
## Figures
**Fig. 1** Study System - *Agelenopsis pennsylvanica* (a). The web consists of a retreat where the spider waits for prey to land, fall, or walk on the web sheet (b)

**Fig. 2** Land cover raster with borders for Lincoln, Nebraska, USA city limits (dashed border), University of Nebraska-Lincoln (UNL) City Campus (solid border, a), and Wilderness Park (solid border, b) using the 2019 National Land Cover Data on Land Cover and QGIS (v. 3.16.3-Hannover, ESRI 102704). For visualization and listing of study sites, see Figure S1 and Table S1, respectively

**Fig. 3** Comparison of search distance (a), the number of webs (b) and spiders (c) in a 10-meter radius of the focal web, the distance from the focal web to the first (d) and second (e) nearest neighbors, and web height (f) by habitat - urban forest vs urban center. Grey jittered points represent the raw data while black points and error bars represent the mean and 95% confidence intervals, respectively, from model predictions. Models were either Poisson Generalized Linear Models (a-c) or Poisson Generalized Linear Mixed Effect Models with site as a random factor (d-f). Asterisks (A-B) indicate significance level (*** *P* < 0.001; ** *P* < 0.01; * *P* < 0.05). We searched shorter distances from the start site to the focal web (a), found more webs (b) and spiders (c) in a 10-meter radius of the focal web, measured shorter distances between the focal web and the two nearest neighbors (d-e), and recorded shorter web heights (f) in the urban center than the urban forest

**Fig. 4** Significant correlations between measures of abundance (number of webs and spiders) and the environmental predictors for the urban center subset. Spectral radiance and road disturbance were dropped from both models of abundance for the urban center subset after AIC model selection. All environmental predictors of abundance were dropped from the urban forest subset. The regression lines and shaded regions represent the predictions and 95% confidence intervals (respectively) from the top Poisson Generalized Linear Model after AIC selection. The points represent the raw data. Asterisks indicate significance level (*** *P* < 0.001; ** *P* < 0.01; * *P* < 0.05)

**Fig. 5** Significant correlations between the aggregation measure (nearest neighbor distance) and the environmental predictors for the urban forest subset (plant species richness, tree cover, and road and highway disturbance) and the urban center subset (plant species richness, spectral radiance, and total road length). All other environmental predictors were dropped from models of nearest neighbor distance after AIC model selection. The regression lines and shaded regions represent the predictions and 95% confidence intervals (respectively) from the top Poisson Generalized Linear Model after AIC selection. The points represent the raw data. Asterisks indicate significance level (*** *P* < 0.001; ** *P* < 0.01; * *P* < 0.05)

## Tables
**Table. 1** Landscape variables for Lincoln (Nebraska, USA) City Limits, University of Nebraska-Lincoln (UNL) City Campus, and Wilderness Park collected from the National Land Cover Database (2016 Tree Cover, 2019 Impervious Cover, 2019 Land Cover), the Landsat-7 World Reference System-2 (Band 6, path 28, row 32, taken September 2, 2020), and the 2020 Visible Infrared Imaging Radiometer Suite (VIIRS) using QGIS (v. 3.16.3-Hannover, ESRI 102704)

**Table 2** Mean and standard error of environmental predictors collected in 100 meter buffers of each focal web by habitat

**Table.3** Results of the top models after AIC model selection from Poisson Generalized Linear Models with the environmental predictors for data overall and subset by habitat (urban forest and urban center). Asterisks indicate significance level (*** *P* < 0.001; ** *P* < 0.01; * *P* < 0.05)
